# Generated by Django 4.2.3 on 2023-07-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='imagen',
            field=models.ImageField(default='blog/img.jpg', upload_to='blog'),
        ),
    ]
