# Generated by Django 4.2.3 on 2023-07-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_usuarios_is_active_alter_usuarios_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='apellido',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
